sudo: false
language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
before_install:
- cd picturepoint
- npm update
install:
- npm install
script:
- npm test
<<<<<<< HEAD
=======

>>>>>>> parent of e3cbd41... Trying to Jest test through coveralls. #108
